apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-prod1

spec:
  replicas: 3

  selector:
    matchLabels:
      app: nginx-prod1

  template:
    metadata:
      labels:
        app: nginx-prod1

    spec:

      # tolerations:
      # - key: "env"
      #   operator: "Equal"
      #   value: "prod"
      #   effect: "NoSchedule"

      containers:
      - name: nginx
        image: nginx:latest

        ports:
        - containerPort: 80
